logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: api-gateway
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}
