spring:
  application:
    name: config-service

  cloud:
    config.server.git:
      uri: https://github.com/Anuj-Kumar-Sharma/lovable-config-server
      username: anuj-kumar-sharma
      password: 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
      default-label: master

server.port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    config:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: k8s

  cloud:
    discovery:
      enabled: false
    config.server.git:
      uri: https://github.com/Anuj-Kumar-Sharma/lovable-config-server
      username: ${GIT_USERNAME}
      password: ${GIT_PASSWORD}

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false